executor: cluster-generic
cluster-generic-submit-cmd: "qsub -cwd \
             -o logs/cluster/{rule}_{wildcards}.cluster.out \
             -e logs/cluster/{rule}_{wildcards}.cluster.err \
             -j y \
             -l h_rt={resources.runtime}:00:00,h_data={resources.mem_gb}G{resources.pe_flag} -pe shared {resources.cpus} \
             -M {params.email} \
             -m bea"
default-resources:
  - runtime=6
  - mem_gb=20
  - cpus=1
  - pe_flag=""
jobs: 30 # capping the max concurrent jobs to avoid overwhelming AppEEARS with requests (each job = ~4 appeears jobs)
latency-wait: 30
keep-going: true
rerun-incomplete: true
cluster-generic-cancel-cmd: "qdel"