### GENERAL SETTINGS ####
NOTIFY_EMAIL: 'caderanek@g.ucla.edu'
ROI: 'data/ROI/california.shp'
START_YEAR: 1990
END_YEAR: 2020

### GET_BASELAYERS ####
LANDFIRE_PRODUCTS: 
  # Topo
  Asp:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_Asp_220_CONUS.zip'
    checksum: 'bbd49eaf6c9cae26c0b3e6d532907b98'
    size_gb: 8.47 
    dir_name: 'data/baselayers/temp/Asp/'

  Elev:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_Elev_220_CONUS.zip'
    checksum: 'd1741fb0feed925e529a97e1a859d1f6'
    size_gb: 8.41
    dir_name: 'data/baselayers/temp/Elev/'

  Slope:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_SlpD_220_CONUS.zip'
    checksum: '8b030a77cb457b25ca75215821cb7c9e'
    size_gb: -1
    dir_name: 'data/baselayers/temp/Slp/'

  # Disturbance
  Disturbance:
    link: 'https://landfire.gov/data-downloads/AnnualDist/AnnualDisturbance_1999_present.zip'
    checksum: 'e10283678d922c97a1d1bd53dd1d5174'
    size_gb: 1.6
    dir_name: 'data/baselayers/temp/US_DIST/'

RAP_PRODUCTS:
  veg_cover_link_prefix: '/vsicurl/http://rangeland.ntsg.umt.edu/data/rap/rap-vegetation-cover/v3/' # Script will add .tif info for years from 1989-2024
  checksum_ref: 'data/baselayers/downloadlogs_metadata/RAP/rap_checksum_filenames.csv'
  dir_name: 'data/baselayers/temp/RAP/'


BASELAYERS:
  topo: 
    fname: 'data/baselayers/asp_slope_anydist.nc'
    dtype: ''
    var_names: []
    dims: []
  annual_dist: 
    fname: 'data/baselayers/annual_dist_withagrdevmask.nc'
    dtype: ''
    nodataval: 0 # meaning, we have no record of disturbance here
    var_names: []
    dims: []
  groupings: 
    fname: 'data/baselayers/annual_veg_grouping_withagrdevmask.nc'
    dtype: ''
    var_names: []
    dims: []
  mtbs_sev:
    fname: 'data/baselayers/annual_mtbs_sev.nc'
    dtype: ''
    var_names: []
    dims: []
  mtbs_poly:
    fname: 'data/baselayers/all_mtbs_poly.shp'