### GENERAL SETTINGS ####
NOTIFY_EMAIL: 'caderanek@g.ucla.edu'
ROI: 'data/ROI/california.shp'
RECOVERY_MAPS_DIR: 'data/recovery_maps/'


### RECOVERY PARAMETERS ####
START_YEAR: 1990
END_YEAR: 2020
ELEV_BANDS_METERS: 500


### GET_BASELAYERS ####
LANDFIRE_PRODUCTS: 
  # Topo
  Asp:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_Asp_220_CONUS.zip'
    checksum: 'bbd49eaf6c9cae26c0b3e6d532907b98'
    size_gb: 8.47 
    dir_name: 'data/baselayers/temp/Asp/'

  Elev:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_Elev_220_CONUS.zip'
    checksum: 'd1741fb0feed925e529a97e1a859d1f6'
    size_gb: 8.41
    dir_name: 'data/baselayers/temp/Elev/'

  Slope:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_SlpD_220_CONUS.zip'
    checksum: '8b030a77cb457b25ca75215821cb7c9e'
    size_gb: -1
    dir_name: 'data/baselayers/temp/Slp/'

  Disturbance:
    link: 'https://landfire.gov/data-downloads/AnnualDist/USAnnualDisturbance_1999_present.zip'
    checksum: '6d8113b25dae963fc5080dc4a3d8fd52'
    size_gb: 1.6
    dir_name: 'data/baselayers/temp/US_DIST/'
    start_year: 1999
    end_year: 2025


NLCD:
  annual_nlcd_link: 'https://www.mrlc.gov/downloads/sciweb1/shared/mrlc/data-bundles/Annual_NLCD_LndCov_YEAR_CU_C1V1.zip' # Script will replace YEAR with year desired
  dir_name: 'data/baselayers/temp/NLCD/'
  vegcodes_csv: 'data/baselayers/downloadlogs_metadata/NLCD/vegcodes_summary.csv'


WUMI_PRODUCTS:
  data_dir: 'data/baselayers/temp/WUMI2024a/fire_maps/'
  projection_raster: 'data/baselayers/temp/WUMI2024a/az3135011111020160516_20160502_20160603_dnbr6.tif'
  subfires_csv_f: 'data/baselayers/temp/WUMI2024a/WUMI2024a_final_wildfire_lists/WUMI2024a_wildfires_1984_2024_with_subfires.txt'
  mtbs_rasters_dir: 'data/baselayers/temp/mtbs_sev_rasters/'

BASELAYERS:
  agdev_mask: 
    fname: 'data/baselayers/agdev_mask.tif'
    dtype: 'int8'
    var_names: []
    dims: []
  topo: 
    fname: 'data/baselayers/topo.nc'
    dtype: ''
    var_names: []
    dims: []
  annual_dist: 
    fname: 'data/baselayers/annual_dist.nc'
    dtype: 'int8'
    nodataval: 0 # meaning, we have no record of disturbance here
    var_names: []
    dims:
      xdim: 'x'
      ydim: 'y'
      timedim: 'time'
  groupings: 
    fname: 'data/baselayers/annual_veg_grouping.nc'
    dtype: ''
    var_names: []
    dims: []