### GENERAL SETTINGS ####
NOTIFY_EMAIL: 'caderanek@g.ucla.edu'
ROI: 'data/ROI/california.shp'
RECOVERY_MAPS_DIR: 'data/recovery_maps/'


### RECOVERY PARAMETERS ####
START_YEAR: 1990
END_YEAR: 2020
ELEV_BANDS_METERS: 500


### GET_BASELAYERS ####
LANDFIRE_PRODUCTS: 
  # Topo
  Asp:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_Asp_220_CONUS.zip'
    checksum: 'bbd49eaf6c9cae26c0b3e6d532907b98'
    size_gb: 8.47 
    dir_name: 'data/baselayers/temp/Asp/'

  Elev:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_Elev_220_CONUS.zip'
    checksum: 'd1741fb0feed925e529a97e1a859d1f6'
    size_gb: 8.41
    dir_name: 'data/baselayers/temp/Elev/'

  Slope:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_SlpD_220_CONUS.zip'
    checksum: '8b030a77cb457b25ca75215821cb7c9e'
    size_gb: -1
    dir_name: 'data/baselayers/temp/Slp/'

  Disturbance:
    link: 'https://landfire.gov/data-downloads/AnnualDist/USAnnualDisturbance_1999_present.zip'
    checksum: '6d8113b25dae963fc5080dc4a3d8fd52'
    size_gb: 1.6
    dir_name: 'data/baselayers/temp/US_DIST/'
    start_year: 1999
    end_year: 2025

  EVT_2001:
    link: 'https://landfire.gov/data-downloads/US_105/US_105_EVT.zip'
    checksum: '3fc7060826d51f79f3a35e4abc3bf35c'
    size_gb: 3.16
    dir_name: 'data/baselayers/temp/EVT/'

  EVT_2016:
    link: 'https://landfire.gov/data-downloads/US_200/LF2016_EVT_200_CONUS.zip'
    checksum: '4b31eb36ef71906c28536b850c8419dd'
    size_gb: 3.43
    dir_name: 'data/baselayers/temp/EVT/'

  EVT_2020:
    link: 'https://landfire.gov/data-downloads/US_220/LF2020_EVT_220_CONUS.zip'
    checksum: '73f6582b1fb848929d659f6c819a4314'
    size_gb: 3.66
    dir_name: 'data/baselayers/temp/EVT/'

  EVT_2022:
    link: 'https://landfire.gov/data-downloads/US_230/LF2022_EVT_230_CONUS.zip'
    checksum: '7bf70b6a2f2c90c36e770649347168c7'
    size_gb: 2.61
    dir_name: 'data/baselayers/temp/EVT/'

  EVT_2023:
    link: 'https://landfire.gov/data-downloads/US_240/LF2023_EVT_240_CONUS.zip'
    checksum: '4b1ec30a29126bea3b78e56a92e9e473'
    size_gb: 3.79
    dir_name: 'data/baselayers/temp/EVT/'

  EVT_2024:
    link: 'https://landfire.gov/data-downloads/US_250/LF2024_EVT_250_CONUS.zip'
    checksum: '5e6f68a1c88c269b2edc1780688e04d5'
    size_gb: 1.27
    dir_name: 'data/baselayers/temp/EVT/'

NLCD:
  annual_lc_link: 'https://www.mrlc.gov/downloads/sciweb1/shared/mrlc/data-bundles/Annual_NLCD_LndCov_YEAR_CU_C1V1.zip' # Script will replace YEAR with year desired
  dir_name: 'data/baselayers/temp/NLCD/'
  metadata_dir_name: 'data/baselayers/downloadlogs_metadata/NLCD/'

RAP_PRODUCTS:
  veg_cover_link_prefix: '/vsicurl/http://rangeland.ntsg.umt.edu/data/rap/rap-vegetation-cover/v3/' # Script will add .tif info for years from 1989-2024
  checksum_ref: 'data/baselayers/downloadlogs_metadata/RAP/rap_checksum_filenames.csv'
  dir_name: 'data/baselayers/temp/RAP/'


WUMI_PRODUCTS:
  data_dir: 'data/baselayers/temp/WUMI2024a/fire_maps/'
  projection_raster: 'data/baselayers/temp/WUMI2024a/az3135011111020160516_20160502_20160603_dnbr6.tif'
  subfires_csv_f: 'data/baselayers/temp/WUMI2024a/WUMI2024a_final_wildfire_lists/WUMI2024a_wildfires_1984_2024_with_subfires.txt'
  mtbs_rasters_dir: 'data/baselayers/temp/mtbs_sev_rasters/'

BASELAYERS:
  agdev_mask: 
    fname: 'data/baselayers/agdev_mask.tif'
    dtype: 'int8'
    var_names: []
    dims: []
  topo: 
    fname: 'data/baselayers/topo.nc'
    dtype: ''
    var_names: []
    dims: []
  annual_dist: 
    fname: 'data/baselayers/annual_dist.nc'
    dtype: 'int8'
    nodataval: 0 # meaning, we have no record of disturbance here
    var_names: []
    dims:
      xdim: 'x'
      ydim: 'y'
      timedim: 'time'
  groupings: 
    fname: 'data/baselayers/annual_veg_grouping.nc'
    dtype: ''
    var_names: []
    dims: []