### GENERAL SETTINGS ####
NOTIFY_EMAIL: 'caderanek@g.ucla.edu'
ROI: 'data/ROI/california.shp'


### TEST SETTINGS ####
SENSITIVITY_ANALYSIS: False
TESTING: True
TEST_ROI: 'data/test_data/test_ROIS_pts/shulightning_deerlick_ROI.shp'
TEST_FIRE: '20140726_376750_1197830' # El Portal WUMI ID


### RECOVERY PARAMETERS ####
RECOVERY_PARAMS:
  RECOVERY_MAPS_DIR: 'data/recovery_maps/output/'
  RECOVERY_PLOTS_DIR: 'results/plots/'
  RECOVERY_CONFIGS: 'data/recovery_maps/submission_organizer/'
  NDVI_SEARCH_ARG: '*mosaiced.tif'
  START_YEAR: 1999                  # when Landfire disturbance starts
  END_YEAR: 2020
  MIN_SEASONS: 4                    # how long until considered recovered
  ELEV_BANDS_METERS: 500            # grouping params
  NUM_NDVI_GROUPS: 3
  YRS_PREFIRE_MATCHED: 5
  MIN_NUM_MATCHED_PIXELS: 100       # QA params
  MIN_TEMPORAL_COVERAGE_RATIO: 0.8
  NDVI_LOWER_BOUND: 0.2
  NDVI_UPPER_BOUND: 1
  CREATE_INTERMEDIATE_TIFS: True    # data output params
  MAKE_PLOTS: True
  DELETE_NDVI_SEASONAL_TIFS: False
  LOGGING_PROCESS_CSV: 'logs/processing_progress_summary.csv'
  MONTH_SEASON_DICT: {1: '1', 2: '4', 3: '7', 4: '10'}  # turn quarters to first month of quarter
  GROUPING_BAND_FORMAT:
    'pattern': "^(?P<veg_elev_id>\\d{2})(?P<prefire_median_NDVI>\\d{3})$"
    'groups': ['veg_elev_id', 'prefire_median_NDVI']
    'digits': 5


### LANDSAT DOWNLOAD PARAMETERS ####
LANDSAT:
  dir_name: 'data/Landsat/temp/' 
  NDVI_BANDS_DICT:    # which bands to use to calculate NDVI for each LS product; in order of NIR, RED
    4: ['SR_B4', 'SR_B3']
    5: ['SR_B4', 'SR_B3']
    7: ['SR_B4', 'SR_B3']
    8: ['SR_B5', 'SR_B4']
    9: ['SR_B5', 'SR_B4']

  RGB_BANDS_DICT:     # RGB bands, in order, for each LS product
    4: ['SR_B3', 'SR_B2', 'SR_B1']
    5: ['SR_B3', 'SR_B2', 'SR_B1']
    7: ['SR_B3', 'SR_B2', 'SR_B1']
    8: ['SR_B4', 'SR_B3', 'SR_B2']
    9: ['SR_B4', 'SR_B3', 'SR_B2']
  VALID_LAYERS: ['QA_PIXEL', 'QA_RADSTAT', 'QA_AEROSOL', 'SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5'] # Valid layers to use in processing
  PRODUCT_LAYERS:     # which bands to use to calculate NDVI, RGB, cloud mask for each LS product
    'L04.002': ['SR_B4', 'SR_B3', 'SR_B2', 'SR_B1', 'QA_PIXEL']
    'L05.002': ['SR_B4', 'SR_B3', 'SR_B2', 'SR_B1', 'QA_PIXEL']
    'L07.002': ['SR_B4', 'SR_B3', 'SR_B2', 'SR_B1', 'QA_PIXEL']
    'L08.002': ['SR_B5', 'SR_B4', 'SR_B3', 'SR_B2', 'QA_PIXEL']
    'L09.002': ['SR_B5', 'SR_B4', 'SR_B3', 'SR_B2', 'QA_PIXEL']
  DEFAULT_NODATA: -9999
  NUM_YRS_PER_REQUEST: 5


### GET_BASELAYERS ####
LANDFIRE_PRODUCTS: 
  # Topo
  Asp:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_Asp_220_CONUS.zip'
    checksum: 'bbd49eaf6c9cae26c0b3e6d532907b98'
    size_gb: 8.47 
    dir_name: 'data/baselayers/temp/Asp/'

  Elev:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_Elev_220_CONUS.zip'
    checksum: 'd1741fb0feed925e529a97e1a859d1f6'
    size_gb: 8.41
    dir_name: 'data/baselayers/temp/Elev/'

  Slope:
    link: 'https://landfire.gov/data-downloads/US_Topo_2020/LF2020_SlpD_220_CONUS.zip'
    checksum: '8b030a77cb457b25ca75215821cb7c9e'
    size_gb: -1
    dir_name: 'data/baselayers/temp/Slp/'

  Disturbance:
    link: 'https://landfire.gov/data-downloads/AnnualDist/USAnnualDisturbance_1999_present.zip'
    checksum: '6d8113b25dae963fc5080dc4a3d8fd52'
    size_gb: 1.6
    dir_name: 'data/baselayers/temp/US_DIST/'
    start_year: 1999
    end_year: 2025


NLCD:
  annual_nlcd_link: 'https://www.mrlc.gov/downloads/sciweb1/shared/mrlc/data-bundles/Annual_NLCD_LndCov_YEAR_CU_C1V1.zip' # Script will replace YEAR with year desired
  dir_name: 'data/baselayers/temp/NLCD/'
  vegcodes_csv: 'data/baselayers/downloadlogs_metadata/NLCD/vegcodes_summary.csv'


WUMI_PRODUCTS:
  data_dir: 'data/baselayers/manual_downloads/WUMI2024a/fire_maps/'
  projection_raster: 'data/baselayers/manual_downloads/WUMI2024a/az3135011111020160516_20160502_20160603_dnbr6.tif'
  subfires_csv_f: 'data/baselayers/manual_downloads/WUMI2024a/WUMI2024a_final_wildfire_lists/WUMI2024a_wildfires_1984_2024_with_subfires.txt'
  mtbs_rasters_dir: 'data/baselayers/manual_downloads/mtbs_sev_rasters/'

BASELAYERS:
  agdev_mask: 
    fname: 'data/baselayers/merged/agdev_mask.tif'
    dtype: 'int8'
  topo: 
    fname: 'data/baselayers/merged/topo.nc'
  annual_dist: 
    fname: 'data/baselayers/merged/annual_dist.nc'
    dtype: 'int8'
    nodataval: 0 # meaning, we have no record of disturbance here
    dims:
      xdim: 'x'
      ydim: 'y'
      timedim: 'time'
  groupings: 
    fname: 'data/baselayers/merged/annual_veg_grouping.nc'
    summary_csv: 'data/baselayers/merged/annual_veg_groupings_summary.csv'


### SENSITIVITY ANALYSIS PARAMETERS ####
SENSITIVITY:
  MIN_SEASONS: {
    'Default': 4, 
    'Range': [4, 6, 8]
  }
  ELEV_BANDS_METERS: {
    'Default': 500,
    'Range': [250, 500, 1000]
  }
  NUM_NDVI_GROUPS: {
    'Default': 3,
    'Range': [2, 3, 5]
  }
  YRS_PREFIRE_MATCHED: {
    'Default': 5,
    'Range': [3, 5, 10]
  }
  MIN_NUM_MATCHED_PIXELS:  {
    'Default': 250,
    'Range': [100, 250, 500]
  }
  MIN_TEMPORAL_COVERAGE_RATIO:  {
    'Default': 0.8,
    'Range': [0.5, 0.8, 0.9]
  }